In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

In [5]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1D Array

In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


# 2D Array

In [8]:
arr = np.array([[1.1,2.2,3.3],[4.4,5.5,6.6]])
print(arr)
print(arr.ndim)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
2


# 3D Array

In [11]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]
3


In [17]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndim argument.

# Create an array with 5 dimensions and verify that it has 5 dimensions:

In [21]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [22]:
a = np.array([[[[[1,2,3,4]]]]])
print(a)
print(a.ndim)

[[[[[1 2 3 4]]]]]
5


# NumPy Array Indexing

Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.
The indexes in NumPy arrays stat with 0, meaning that the first element has index 0, and the second has index 1 etc.

# Get the first element from the following array:

In [23]:
arr = np.array([1,2,3,4])

print(arr[0])

1


# Get third and sixth and 8th elements from the following array and add them.

In [24]:
m = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
print("the third element is", m[2])
print("the sixth element is", m[5])
print("the 8th element is", m[7])
print("sum of this elements are", m[2]+m[5]+m[7])

the third element is 34.0
the sixth element is 90.0
the 8th element is 10.0
sum of this elements are 134.0


# 2D Array Indexing

In [25]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  20


In [26]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('4th element on 1st row: ', arr[0,3])

4th element on 1st row:  40


In [27]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('1st element on 2nd row: ', arr[1,0])

1st element on 2nd row:  60


In [28]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('last element on 2nd row: ', arr[1,4])

last element on 2nd row:  100


# Add the first element of row 1 and last element

In [29]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('First element of 1st row: ', arr[0,0])
print('Last element of 2nd row: ', arr[1,4])
print("Sum is" , arr[0,0]+arr[1,4])

First element of 1st row:  10
Last element of 2nd row:  100
Sum is 110


# Access 3D Arrays

To access elements from 3D arrays we can use comma seprated integers representing the dimensions and the index of the element.

# Access the third element of the second array of the first array:

In [30]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


In [31]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[1,1,2])

12


In [32]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[1,0,1])

8


In [33]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[1,1,1])

11


In [34]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[1,0,0])

7


In [35]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,1])

5
